[package]
name = "scarab"
version = "0.1.0"
authors = ["Alexander Michael Feetham <123alexfeetham@gmail.com>"]

# Building a static library
[lib]
crate-type = ["staticlib"]

# a basic libc implementation
#[dependencies]
#rlibc = "1.0"
